// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtFsiXfqeo-AXZted8nDyaWJqv_dI7epE',
    appId: '1:552221493739:web:e506e1580f909219e471ae',
    messagingSenderId: '552221493739',
    projectId: 'json-parser-app',
    authDomain: 'json-parser-app.firebaseapp.com',
    storageBucket: 'json-parser-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChrmMKFaeWPAJffgjpN3rpzhiYab44kyE',
    appId: '1:552221493739:android:b6da149c3cfe4a35e471ae',
    messagingSenderId: '552221493739',
    projectId: 'json-parser-app',
    storageBucket: 'json-parser-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOl1IJLas8wWkiSZOBvulpaaOtjUtCJkk',
    appId: '1:552221493739:ios:749d3e27332b66c6e471ae',
    messagingSenderId: '552221493739',
    projectId: 'json-parser-app',
    storageBucket: 'json-parser-app.firebasestorage.app',
    iosBundleId: 'com.example.jsonReaderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOl1IJLas8wWkiSZOBvulpaaOtjUtCJkk',
    appId: '1:552221493739:ios:749d3e27332b66c6e471ae',
    messagingSenderId: '552221493739',
    projectId: 'json-parser-app',
    storageBucket: 'json-parser-app.firebasestorage.app',
    iosBundleId: 'com.example.jsonReaderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtFsiXfqeo-AXZted8nDyaWJqv_dI7epE',
    appId: '1:552221493739:web:9f4769bd791674d6e471ae',
    messagingSenderId: '552221493739',
    projectId: 'json-parser-app',
    authDomain: 'json-parser-app.firebaseapp.com',
    storageBucket: 'json-parser-app.firebasestorage.app',
  );
}
