name: finance_navigator
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.2.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  meta: ^1.17.0        # Update this line
  test_api: ^0.7.10    # Update this line
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  active_icon_foreground: "#ffffff"
  active_icon_background: "assets/play_store_512.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/splash.png
  image_dark: assets/splash_dark.png
  
  android_12:
    color: "#ffffff"
    color_dark: "#272727"
    image: assets/splash.png
    image_dark: assets/splash_dark.png

  web: false

flutter:

  uses-material-design: true

