// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC789Gue3RAmUdO8aweqbt_MiR_CjiuOT4',
    appId: '1:70750065893:web:88a9b55acfe520e731b00c',
    messagingSenderId: '70750065893',
    projectId: 'student-registration-6426e',
    authDomain: 'student-registration-6426e.firebaseapp.com',
    storageBucket: 'student-registration-6426e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBlMlwxKIeyPDzdj5fxiQyxD1CUjKX8Gk',
    appId: '1:70750065893:android:f771cf72f4bda6ad31b00c',
    messagingSenderId: '70750065893',
    projectId: 'student-registration-6426e',
    storageBucket: 'student-registration-6426e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIM61__cCqx2LvUyWZkiSI9SbF7E3NcPc',
    appId: '1:70750065893:ios:5e032afc3bda424931b00c',
    messagingSenderId: '70750065893',
    projectId: 'student-registration-6426e',
    storageBucket: 'student-registration-6426e.firebasestorage.app',
    iosBundleId: 'com.example.studentRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIM61__cCqx2LvUyWZkiSI9SbF7E3NcPc',
    appId: '1:70750065893:ios:5e032afc3bda424931b00c',
    messagingSenderId: '70750065893',
    projectId: 'student-registration-6426e',
    storageBucket: 'student-registration-6426e.firebasestorage.app',
    iosBundleId: 'com.example.studentRegistrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC789Gue3RAmUdO8aweqbt_MiR_CjiuOT4',
    appId: '1:70750065893:web:6b5763ec4719ee7e31b00c',
    messagingSenderId: '70750065893',
    projectId: 'student-registration-6426e',
    authDomain: 'student-registration-6426e.firebaseapp.com',
    storageBucket: 'student-registration-6426e.firebasestorage.app',
  );
}
