import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const StudentRegistrationApp());
}

class StudentRegistrationApp extends StatelessWidget {
  const StudentRegistrationApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.indigo, useMaterial3: true),
      home: const RegistrationForm(),
    );
  }
}

// ─── SCREEN 1: REGISTRATION FORM ─────────────────────────────────────────────

class RegistrationForm extends StatefulWidget {
  const RegistrationForm({super.key});

  @override
  State<RegistrationForm> createState() => _RegistrationFormState();
}

class _RegistrationFormState extends State<RegistrationForm> {
  final _formKey = GlobalKey<FormState>();
  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _newClassController = TextEditingController();

  // Reference to the Firestore collection (replaces DatabaseHelper)
  final _firestore = FirebaseFirestore.instance;

  String? _selectedClass;
  List<String> _classList = [];

  @override
  void initState() {
    super.initState();
    _loadClasses();
  }

  // READ: Fetch all class names from the "classes" collection
  Future<void> _loadClasses() async {
  final snapshot = await _firestore
      .collection('classes')
      .orderBy('name')
      .get();

  print('Docs found: ${snapshot.docs.length}'); // ← add this
  for (var doc in snapshot.docs) {
    print('Class: ${doc.data()}');               // ← and this
  }

  setState(() {
    _classList = snapshot.docs
        .map((doc) => doc['name'] as String)
        .toList();
  });
}

  // WRITE: Add a new class document to the "classes" collection
  Future<void> _addClass() async {
    final name = _newClassController.text.trim();
    if (name.isEmpty) return;

    // Check for duplicates before inserting
    final existing = await _firestore
        .collection('classes')
        .where('name', isEqualTo: name)
        .get();

    if (existing.docs.isEmpty) {
      await _firestore.collection('classes').add({'name': name});
      _newClassController.clear();
      _loadClasses();
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('That class already exists.')),
      );
    }
  }

  String? _nameValidator(String? value) {
    if (value == null || value.isEmpty) return 'This field is required';
    final nameRegExp = RegExp(r"^[a-zA-Z\s]+$");
    if (!nameRegExp.hasMatch(value)) {
      return 'Please enter text only (no numbers or symbols)';
    }
    return null;
  }

  // WRITE: Add a new student document to the "students" collection
  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      await _firestore.collection('students').add({
        'first_name': _firstNameController.text.trim(),
        'last_name': _lastNameController.text.trim(),
        'class_name': _selectedClass,
        'registered_at': FieldValue.serverTimestamp(), // bonus: auto timestamp
      });

      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => ResultScreen(
            firstName: _firstNameController.text,
            lastName: _lastNameController.text,
            className: _selectedClass!,
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Class Registration")),
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              const Text(
                "Student Enrollment",
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 20),

              // First Name
              TextFormField(
                controller: _firstNameController,
                decoration: const InputDecoration(
                  labelText: "First Name",
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.person),
                ),
                validator: _nameValidator,
              ),
              const SizedBox(height: 15),

              // Last Name
              TextFormField(
                controller: _lastNameController,
                decoration: const InputDecoration(
                  labelText: "Last Name",
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.person_outline),
                ),
                validator: _nameValidator,
              ),
              const SizedBox(height: 15),

              // Class Dropdown (populated from Firestore)
              DropdownButtonFormField<String>(
                decoration: const InputDecoration(
                  labelText: "Select a Class",
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.school),
                ),
                value: _selectedClass,
                items: _classList.map((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value),
                  );
                }).toList(),
                onChanged: (newValue) {
                  setState(() => _selectedClass = newValue);
                },
                validator: (value) =>
                    value == null ? 'Please select a class' : null,
              ),
              const SizedBox(height: 15),

              // Add New Class
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _newClassController,
                      decoration: const InputDecoration(
                        labelText: "Add New Class",
                        border: OutlineInputBorder(),
                      ),
                    ),
                  ),
                  const SizedBox(width: 10),
                  ElevatedButton(
                    onPressed: _addClass,
                    child: const Text("ADD"),
                  ),
                ],
              ),
              const SizedBox(height: 30),

              // Submit
              ElevatedButton(
                onPressed: _submitForm,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 15),
                  backgroundColor: Colors.indigo,
                  foregroundColor: Colors.white,
                ),
                child: const Text(
                  "SUBMIT REGISTRATION",
                  style: TextStyle(fontSize: 16),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ─── SCREEN 2: SUCCESS PAGE ───────────────────────────────────────────────────

class ResultScreen extends StatelessWidget {
  final String firstName;
  final String lastName;
  final String className;

  const ResultScreen({
    super.key,
    required this.firstName,
    required this.lastName,
    required this.className,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Registration Successful")),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(30.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.check_circle, color: Colors.green, size: 100),
              const SizedBox(height: 20),
              Text(
                "$firstName $lastName has registered for $className",
                textAlign: TextAlign.center,
                style: const TextStyle(
                    fontSize: 20, fontWeight: FontWeight.w500),
              ),
              const SizedBox(height: 40),
              OutlinedButton(
                onPressed: () => Navigator.pop(context),
                child: const Text("BACK TO FORM"),
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () => Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (context) => const StudentsListScreen()),
                ),
                child: const Text("VIEW ALL STUDENTS"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ─── SCREEN 3: STUDENTS LIST ──────────────────────────────────────────────────

class StudentsListScreen extends StatelessWidget {
  const StudentsListScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Registered Students")),
      // StreamBuilder listens for real-time updates from Firestore
      body: StreamBuilder<QuerySnapshot>(
        stream: FirebaseFirestore.instance
            .collection('students')
            .orderBy('last_name')
            .snapshots(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
            return const Center(child: Text("No students registered yet."));
          }

          final students = snapshot.data!.docs;

          return ListView.builder(
            itemCount: students.length,
            itemBuilder: (context, index) {
              final student = students[index].data() as Map<String, dynamic>;
              return ListTile(
                title: Text(
                    "${student['first_name']} ${student['last_name']}"),
                subtitle: Text("Class: ${student['class_name']}"),
              );
            },
          );
        },
      ),
    );
  }
}