// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY0tvl5VsTsP837SrhG2kjt98ippumwSA',
    appId: '1:158304390046:web:0a4ef8307011b1cd86648f',
    messagingSenderId: '158304390046',
    projectId: 'rolodex-app-12539',
    authDomain: 'rolodex-app-12539.firebaseapp.com',
    storageBucket: 'rolodex-app-12539.firebasestorage.app',
    measurementId: 'G-RQZQNZY77R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP-JICTfYDHyv9jdRAcjNdPip-O62Vlx4',
    appId: '1:158304390046:android:7ab8885c19d4d3af86648f',
    messagingSenderId: '158304390046',
    projectId: 'rolodex-app-12539',
    storageBucket: 'rolodex-app-12539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlTlrW_VNZ_fDPH9ZlqDd6gekd7cXqdk',
    appId: '1:158304390046:ios:fabbd3285bd230bf86648f',
    messagingSenderId: '158304390046',
    projectId: 'rolodex-app-12539',
    storageBucket: 'rolodex-app-12539.firebasestorage.app',
    iosBundleId: 'com.example.rolodexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmlTlrW_VNZ_fDPH9ZlqDd6gekd7cXqdk',
    appId: '1:158304390046:ios:fabbd3285bd230bf86648f',
    messagingSenderId: '158304390046',
    projectId: 'rolodex-app-12539',
    storageBucket: 'rolodex-app-12539.firebasestorage.app',
    iosBundleId: 'com.example.rolodexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY0tvl5VsTsP837SrhG2kjt98ippumwSA',
    appId: '1:158304390046:web:421b672a07424aec86648f',
    messagingSenderId: '158304390046',
    projectId: 'rolodex-app-12539',
    authDomain: 'rolodex-app-12539.firebaseapp.com',
    storageBucket: 'rolodex-app-12539.firebasestorage.app',
    measurementId: 'G-SFHGN20BTV',
  );
}
